apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: knative

resources:
- ./manifests/serving-core.yaml
- ./manifests/serving-hpa.yaml
- ./manifests/net-istio.yaml

patches:
  - path: ./patches/config-istio.yaml